# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.
#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`


In [4]:
import numpy as np


In [6]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`

new_vector = np.arange(10,50)

new_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [22]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`

matrix_value = np.arange(0, 9).reshape((3, 3))
matrix_value


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`
arr = np.array([1, 2, 0, 0, 4, 0])

non0 = np.nonzero(arr)[0]
non0

array([0, 1, 4])

In [26]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`

id_mat = np.eye(3,3)
id_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`

random_values = np.random.random((3,3,3))
random_values

array([[[0.60702476, 0.99390181, 0.44337802],
        [0.49911721, 0.93432591, 0.5446542 ],
        [0.47935777, 0.44311743, 0.1093445 ]],

       [[0.95156659, 0.26507606, 0.13009002],
        [0.84129864, 0.90682772, 0.15411923],
        [0.52323161, 0.85375369, 0.57454829]],

       [[0.96349395, 0.65170997, 0.50607651],
        [0.53476202, 0.41684747, 0.14215374],
        [0.01162636, 0.17066114, 0.47973179]]])

In [30]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`
random_values_ten = np.random.random((10,10))
random_values_ten

array([[0.79829208, 0.28261137, 0.35534117, 0.7539872 , 0.22478938,
        0.1740354 , 0.95869176, 0.4243573 , 0.04289039, 0.20607223],
       [0.68941384, 0.11271183, 0.90794877, 0.69101337, 0.34428872,
        0.30751148, 0.41642071, 0.67671914, 0.8713338 , 0.81036977],
       [0.527109  , 0.11580888, 0.27597222, 0.66116186, 0.4447083 ,
        0.29654147, 0.75927593, 0.73057351, 0.67930121, 0.13431521],
       [0.98462277, 0.4371653 , 0.57378282, 0.61790535, 0.9859003 ,
        0.38782518, 0.45906924, 0.20954761, 0.60370025, 0.08291496],
       [0.08649208, 0.37629074, 0.16045402, 0.36076203, 0.44652173,
        0.34319266, 0.8101589 , 0.70425752, 0.07961389, 0.71495107],
       [0.35080253, 0.11255942, 0.43911113, 0.25545187, 0.6795913 ,
        0.07771104, 0.82116428, 0.36968146, 0.96682681, 0.37108349],
       [0.5975572 , 0.9951313 , 0.38612161, 0.17914331, 0.74655747,
        0.38775705, 0.4119625 , 0.73632887, 0.72313279, 0.74988007],
       [0.78251618, 0.13354811, 0.3172483

In [34]:
min_rvt = np.min(random_values_ten)

min_rvt


0.042890389448516975

In [35]:
max_rvt = np.max(random_values_ten)

max_rvt

0.9951312956517868

In [37]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
random_vector = np.random.rand(30)

random_vector

array([0.66200632, 0.74993225, 0.79522728, 0.59452966, 0.89625464,
       0.6853771 , 0.25422408, 0.66075347, 0.98655328, 0.76590727,
       0.11549705, 0.59888009, 0.27482772, 0.55940803, 0.72783967,
       0.63334733, 0.38547694, 0.91468389, 0.08312864, 0.21298101,
       0.71200136, 0.26550843, 0.00135971, 0.03478297, 0.59207253,
       0.93556817, 0.89092863, 0.93284793, 0.59268557, 0.04622527])

In [38]:
mean_value = np.mean(random_vector)
mean_value

0.5520272098790088

In [43]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`

five_mat = np.diag([1,2,3,4], k = -1)
five_mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [44]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`

ran_mat = np.random.rand(5, 5)
normalized_matrix = (ran_mat - np.mean(ran_mat)) / np.std(ran_mat)

normalized_matrix

array([[ 0.47328532, -0.94259413, -0.47127074,  0.08591806, -0.51394594],
       [ 1.63972501, -1.11416722,  1.14566333, -1.19915386, -0.57493618],
       [-0.88066206, -1.16412522,  1.62101759, -0.7344241 ,  0.41542709],
       [ 0.61570696,  0.65320326,  1.45905464, -0.20043637,  1.33207266],
       [-1.10592595, -1.2288123 , -0.00164589,  1.60871155, -0.91768551]])

In [45]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`
    
arr1 = np.array([1,4,2,5,3,8])
arr2 = np.array([5,9,0,4,1,7])
common_value = np.intersect1d(arr1, arr2)
common_value

array([1, 4, 5])

In [55]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`

rand_vect = np.random.rand(10)

sorted_vect = np.sort(rand_vect)

sorted_vect

array([0.12672356, 0.42841107, 0.43416915, 0.54420223, 0.54659831,
       0.63552794, 0.68220407, 0.79827606, 0.85963475, 0.96654687])

In [59]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`

rand_vect = np.random.rand(10)
max_value = np.argmax(rand_vect)
rand_vect[max_value] = 0

rand_vect


array([0.42435375, 0.77488827, 0.39510853, 0.14670289, 0.93608425,
       0.22357296, 0.24842763, 0.9237434 , 0.        , 0.91756404])

In [84]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)`

x = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(x, axis=1)
result = x - row_means[:, np.newaxis]
print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [91]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
#hint: np.argsort | np.argpartition`

large_value = np.argsort(Z)[-n:]

large_value


array([8013, 9111, 5933, 4732, 8987])

In [94]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
matrix = np.random.rand(5,3)
    
matrix = np.where(matrix > 4, matrix **2, matrix)

matrix



array([[0.70592065, 0.32253021, 0.93388265],
       [0.13919   , 0.73965567, 0.66466452],
       [0.77509772, 0.34899215, 0.25537697],
       [0.05380896, 0.9913126 , 0.57768316],
       [0.76699178, 0.46134606, 0.80336802]])